# Generated by Django 3.1.4 on 2020-12-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pawn', 'Pawn'), ('Bishop', 'Bishop'), ('Knight', 'Knight'), ('Rook', 'Rook'), ('Queen', 'Queen'), ('King', 'King')], max_length=6)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=5)),
            ],
        ),
    ]
