name: Python application

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Copying configurations
      run: |
        cp contrib/env-sample .env
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 .
    - name: Test with pytest
        run: |
          pipenv run coverage run manage.py test
    - name: Posting Coverage
        env:
          CODECOV_TOKEN: "d731f8dc-7258-44ff-9c83-329fc9999ab6"
        run: |
          pipenv run codecov

